services:
  backend:
    container_name: backend
    image: ghcr.io/zhliau/fika-spt-server-docker:3.11.3
    environment:
      - INSTALL_FIKA=true
      - LISTEN_ALL_NETWORKS=true
      - AUTO_UPDATE_FIKA=true
      - AUTO_UPDATE_SPT=false
      - TAKE_OWNERSHIP=false
      - CHANGE_PERMISSIONS=false
      - TZ=America/Denver
      - NUM_HEADLESS_PROFILES=2
    volumes:
      - /mnt/md0/sptd-test/backend:/opt/server:Z
    network_mode: host

  hc1:
    container_name: hc1
    image: ghcr.io/zhliau/fika-headless-docker:v2.1.0
    volumes:
      - /mnt/md0/sptd-test/hc1:/opt/tarkov:Z
    # devices:
    #   - /dev/ntsync:/dev/ntsync
    environment:
      - SERVER_URL=host.containers.internal
      - SERVER_PORT=6969
      - FSYNC=false
      - ENABLE_LOG_PURGE=false
      - USE_MODSYNC=true
      - PROFILE_ID=68253357ab4d3800210023a5
    network_mode: host
    # ports:
    #   - 25565:25565/udp

  hc2:
    container_name: hc2
    image: ghcr.io/zhliau/fika-headless-docker:v2.1.0
    volumes:
      - /mnt/md0/sptd-test/hc2:/opt/tarkov:Z
    # devices:
    #   - /dev/ntsync:/dev/ntsync
    environment:
      - SERVER_URL=host.containers.internal
      - SERVER_PORT=6969
      - FSYNC=false
      - ENABLE_LOG_PURGE=false
      - USE_MODSYNC=true
      - PROFILE_ID=68253357ab4d380021002267
    network_mode: host
    # ports:
    #   - 25566:25566/udp
