# Config
base_dir := "/mnt/md0/sptd-test"
clients := "4"


# Autogenerated Values
backend_dir := base_dir / "backend"
client_dir := base_dir / "hc"

config_dir := base_dir / "config"
mods_dir := base_dir / "mods"

status:
    podman-compose ps

stats:
    podman-compose stats

logs TARGET:
    podman-compose logs -f {{TARGET}}

start: rm-client-mods
    podman-compose up -d backend hc{1..{{clients}}}

stop:
    podman-compose down

list-players:
    curl --silent -X GET -H "responsecompressed: 0" https://localhost:6969/fika/presence/get | jq

list-headless:
    curl --silent -X GET -H "responsecompressed: 0" https://localhost:6969/fika/headless/available -k | jq

broadcast MESSAGE:
    curl -k --output /dev/null -X POST -H "requestcompressed: 0" \
    -H "Content-Type: application/json" \
    -d '{"notification": "{{MESSAGE}}", "notificationIcon": 0}' \
    https://localhost:6969/fika/notification/push

restart: stop start

restart-clients:
    podman-compose restart hc{1..{{clients}}}

restart-backend:
    podman-compose restart backend

copy-mods:
    cp -rv /export/public/mods/* {{backend_dir}}
    cp -r /export/public/mods/* {{base_dir}}/hc1
    cp -r /export/public/mods/* {{base_dir}}/hc2
    cp -r /export/public/mods/* {{base_dir}}/hc3
    cp -r /export/public/mods/* {{base_dir}}/hc4

list-mods:
    ls -1d {{backend_dir}}/user/mods/*
    find {{backend_dir}}/BepInEx/plugins -name "*.dll"

cleanup:
    find {{base_dir}} -name "LICENSE-*" -delete -print

dry-cleanup:
    find {{base_dir}} -name "LICENSE-*"

backup:
    cp -r {{base_dir}} {{base_dir}}-backups/sptd_$(date --iso-8601=seconds)

ln-configs:
    stow --dir=config --target=. -R {{base_dir}}/backend {{base_dir}}/hc1 {{base_dir}}/hc2 {{base_dir}}/hc3 {{base_dir}}/hc4

set-configs:
    # set correct ports for hc2 & hc3
    sed -i 's/UDP Port = 25565/UDP Port = 25566/' {{base_dir}}/hc2/BepInEx/config/com.fika.core.cfg
    sed -i 's/UDP Port = 25565/UDP Port = 25567/' {{base_dir}}/hc3/BepInEx/config/com.fika.core.cfg
    sed -i 's/UDP Port = 25565/UDP Port = 25568/' {{base_dir}}/hc4/BepInEx/config/com.fika.core.cfg

    #make sure MOAR preset is correctly set
    sed -i 's/Moar Preset = .*/Moar Preset = Random/' {{base_dir}}/hc1/BepInEx/config/MOAR.settings.cfg
    sed -i 's/Moar Preset = .*/Moar Preset = Random/' {{base_dir}}/hc2/BepInEx/config/MOAR.settings.cfg
    sed -i 's/Moar Preset = .*/Moar Preset = Random/' {{base_dir}}/hc3/BepInEx/config/MOAR.settings.cfg
    sed -i 's/Moar Preset = .*/Moar Preset = Random/' {{base_dir}}/hc4/BepInEx/config/MOAR.settings.cfg

rm-client-mods:
    rm -rf {{base_dir}}/hc1/BepInEx/client
    rm -rf {{base_dir}}/hc2/BepInEx/client
    rm -rf {{base_dir}}/hc3/BepInEx/client
    rm -rf {{base_dir}}/hc4/BepInEx/client

    rm -rf {{base_dir}}/hc1/user/mods
    rm -rf {{base_dir}}/hc2/user/mods
    rm -rf {{base_dir}}/hc3/user/mods
    rm -rf {{base_dir}}/hc4/user/mods
